# Setup
title:         Zhibin Qiu
tagline:      A responsive theme for your project on GitHub Pages
#baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Zhibin Qiu
  url:        https://zhibinQiu.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
plugins: [jekyll-paginate]

domain: zhibinQiu.github.io 
url: https://zhibinQiu.github.io   # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /REPOSITORY-NAME/ 